spring.application.name=VinayKumdale_Task1

spring.datasource.url=jdbc:mysql://localhost:3306/Atm
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

